default: true

# Using h2 has side effects in GitBook's toc. Thus, we sometimes switch from h1 to h3
MD001: false

# GitBook mixes * and - as list styles
MD004: false

# Something goes wrong with the lists with GitBook
MD007: false

# GitBook keeps adding and adding blank lines, thus disabled
MD012: false

MD013: false

# We have "{% tab title="Windows" %}" directly above a heading
MD022:
  lines_above: 0
  lines_below: 1

# We may have duplicate headings (e.g., #### Examples in en/collect/import-using-online-bibliographic-database.md)
MD024: false

# The FAQs state questions - we allow them
MD026:
  punctuation: ".,;:!"

MD033:
  # we have <a> tags with ids
  allowed_elements: ['a', 'div', 'figure', 'figcaption', 'img', 'p', 'mark']

# we allow images without alt text
MD045: false
