name: Check links
on:
  push:
    paths:
      - '.github/workflows/check-links.yml'
      - '**/*.md'
  pull_request:
  schedule:
    - cron: "0 9 1 * *"
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
